# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

username="{用户名}"
password="{密码}"
signin_id=1 # 按钮id


class TestMain():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_main(self):
    self.driver.get("http://ehall.seu.edu.cn/new/index.html")
    self.driver.set_window_size(855, 473)
    self.driver.find_element(By.CSS_SELECTOR, ".amp-no-login-zh").click()
    self.driver.find_element(By.ID, "username").send_keys(username)
    self.driver.find_element(By.ID, "password").send_keys(password)
    self.driver.find_element(By.ID, "xsfw").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(2) > span").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".appitem:nth-child(signin_id) .title > span").click()
    self.vars["win6281"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6281"])
    self.driver.find_element(By.CSS_SELECTOR, ".bh-mb-16 > .bh-btn").click()
    self.driver.find_element(By.ID, "save").click()
    self.driver.find_element(By.LINK_TEXT, "确认").click()
  
